# Generated by Django 4.2.7 on 2023-12-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='real_estate',
            new_name='real_estate_object',
        ),
    ]
