# Generated by Django 4.2.7 on 2024-01-06 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0002_rename_real_estate_lease_real_estate_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='арендатор', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='cadastral_number',
            field=models.CharField(max_length=255, verbose_name='Кадастровый номер'),
        ),
    ]
