# Generated by Django 4.2.7 on 2024-01-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_alter_lease_address_alter_lease_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='real_estate_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='объект_недвижимости', to='real_estate.realestateobject'),
        ),
    ]
