# Generated by Django 4.2.7 on 2024-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_alter_lease_real_estate_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='description',
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='cadastral_number',
            field=models.CharField(max_length=255),
        ),
    ]
